services:
  postgres:
    image: postgres:16-alpine
    container_name: cloudzent-db

    restart: unless-stopped

    env_file:
      - ./backend/.env

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cloudzent"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - cloudzent-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: cloudzent-backend

    restart: unless-stopped

    env_file:
      - ./backend/.env

    ports:
      - "5000:5000"

    volumes:
      - ./backend:/app
      - /app/node_modules

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - cloudzent-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: cloudzent-frontend

    restart: unless-stopped

    env_file:
      - ./frontend/.env

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    environment:
      - VITE_PROXY_TARGET=http://backend:5000

    depends_on:
      - backend

    networks:
      - cloudzent-network

volumes:
  postgres_data:

networks:
  cloudzent-network: